server:
  port: 8000

spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:msdb
    username: root
    password: root
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
      
  application:
   name: Adminpage-Service  
 
eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    preferIpAddress: true 
   
  client:    
    serviceUrl:
      defaultZone: http://localhost:8761/eureka   

pivotal:
  empservice:
    name: Employee-Service
  adminpageservice:
    name: Adminpage-Service     
management:
  endpoint:
    web:
      exposure:
        include:* 
                  